# Deployment do Conversão temperatura
apiVersion: apps/v1
kind: Deployment
metadata:
  name: conversao-temperatura
spec:
  replicas: 7
  selector:
    matchLabels:
      app: conversao-temperatura
  template:
    metadata:
      labels:
        app: conversao-temperatura
    spec:
      containers:
        - name: conversao-temperatura
          image: hernanisoares/conversaotemperatura:v1
          ports:
            - containerPort: 8080
---
# Service da aplicação web

apiVersion: v1
kind: Service
metadata: 
  name: conversao-temperatura
spec:
  selector:
    app: conversao-temperatura
  ports:
    - port: 8080
      protocol: TCP
      name: http
  type: LoadBalancer